### ISSUE TITLE
Prepare slides for the final presentation

### ISSUE THREAD

**Issue by rschlaefli** [kwizapp/kwiz#27]
# Final Presentation

### Tasks

- [x] Find out if we can use a mobile phone prototype for the demo in the browser?
- [x] prepare slides [here](https://docs.google.com/presentation/d/1PsTCVIvX7GwMeQxlJe9AfKzlDFJeUPsI9xS0pSWN-_U/edit#slide=id.p)

**Comment by nikzaugg** [comment]
Just to have it here also: we are using https://marvelapp.github.io/devices.css/ to demo our application in full-screen mode.
