### ISSUE TITLE
Create API Docs for Microservices and Backend

### ISSUE THREAD

**Issue by nikzaugg** [kwizapp/kwiz#29]
### Description

Provide consistent API documentation.

### Tasks

- [x] Choose an API documentation format (use the same for all API-based services)
  - Can we use the same for GraphQL as we use for REST?
  - E.g., Postman Docs, Swagger, or some other generated format
- [x] Add API documentation to [organization wiki](https://github.com/kwizapp/kwiz/wiki)

### Context 
[Story: Poster API](https://github.com/kwizapp/kwiz/issues/22)

#### From the Project Instructions
You are required to document your project and source code. You should apply an Agile philosophy for the documentation. Try to not postpone the moment for documentation. First of all, we need to understand what you did and how your application works. Second, you are working with other people and a proper documentation is very useful to report the behavior of your code.

First, you have to provide a README.md file in the root of the project, as well as of every micro service you define. As for the source code, you can use a documentation generator for the language you choose, for instance Javadoc. Never forget to document the tests code.

You have then to maintain a wiki for the project. Every GitHub project has a parallel repository where you can store Markdown files to compose the wiki. We are expecting you to describe your project, its architecture, and how to use it. In particular, we want to understand the motivation for all of your choices.

You can use the wiki also to document the usage for the API of the backend. As an alternative, you can use specific API documentation tools, such as Swagger, in the case you decide to use REST.

**Comment by nikzaugg** [comment]
@rschlaefli @alexscheitlin 

We can close this one right? As we are tracking the documentation in https://github.com/kwizapp/kwiz/issues/50

If yes -> close issue.

**Comment by rschlaefli** [comment]
I would leave this open, as the other is just about moving the docs to the wiki, no? @alexscheitlin feel free to close this one if you think differently

**Comment by alexscheitlin** [comment]
This is done by now. I'll close this issue.
