### ISSUE TITLE
Initial project planning

### ISSUE THREAD

**Issue by rschlaefli** [kwizapp/kwiz#4]
- [x] Poster
- [x] Metadata
- [x] Nest
- [x] Ionic
- [x] MVP

**Comment by nikzaugg** [comment]
@rschlaefli , @alexscheitlin 
I've written some user stories, please review/comment/update them.

See issue page for the stories.

**Comment by rschlaefli** [comment]
https://github.com/kwizapp/kwiz/projects/1

**Comment by rschlaefli** [comment]
Went through all of the stories. @alexscheitlin Please review :)

**Comment by rschlaefli** [comment]
Created one-week sprints (1-8). Please assign any issues to a sprint, if already clear when it should be done.

**Comment by alexscheitlin** [comment]
> @rschlaefli , @alexscheitlin
> I've written some user stories, please review/comment/update them.
> 
> See issue page for the stories.

I've reviewed the stories and added some more details to the acceptance criteria.
