### ISSUE TITLE
Document past and current decisions in Wiki

### ISSUE THREAD

**Issue by rschlaefli** [kwizapp/kwiz#6]
### Update Wiki
- [x] Restructure Pages
- [x] Add content from proposal
- [x] Add additional Page about the 'Project Management', where we document our decisions and our workflow

**Comment by nikzaugg** [comment]
@rschlaefli 
just take a quick look and then close issue

I've restructured the Wiki a bit and added parts of the proposal. Don't think we need to add more as of now. We will continuously add more once we start developing.

**Comment by rschlaefli** [comment]
Great! Thanks for your contribution :)
